# codecov.yml
coverage:
  status:
    project: # Configuración para la cobertura general del proyecto
      default:
        target: 80% # Fallar si la cobertura general del proyecto cae por debajo del 80%
        threshold: 1% # Margen de caída permisible
        # Puedes añadir `if_not_found_action: error` si quieres que falle si no se encuentra el reporte
        # Puedes añadir `informational: true` si no quieres que falle, solo que informe

    patch: # Configuración para la cobertura de las líneas CAMBIADAS en el MR
      default:
        target: 85% # Fallar si la cobertura de las líneas nuevas/modificadas es menor al 85%
        # Es muy común poner un target alto (ej. 80-100%) para el patch coverage,
        # ya que los cambios nuevos deben estar bien testeados.
        threshold: 5% # Si el target es 85%, se permitirá hasta un 80% antes de fallar.
        # Solo fallará el CI si la cobertura de los cambios es menor al target - threshold