import "@/components/common/globals.css";
import { StoreProvider } from "@/lib/StoreProvider";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            {children}
            {modal}
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
