import "@/components/common/globals.css";
// import { StoreProvider } from "../../lib/StoreProvider";
// import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Metadata } from "next";
import { ModeToggle } from "@/components/frontbuild/ModeToggle";
import { NextIntlClientProvider } from "next-intl";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Frontbuild",
  description: "Generated by create next app",
};

//TODO, ver como isolar NextIntl de layout ya que falla en tests
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <head />
      <body
        // className={`${geistSans.className} ${geistMono.className}`}
        data-testid="body-frontbuild"
      >
        <NextIntlClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            <ModeToggle />
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
