name: "Chromatic"

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Next.js (with export)
        working-directory: ./frontend
        run: npm run build  # Genera los archivos estáticos en `out`

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: ./frontend/out  # Usa la carpeta de salida generada por `next build`
          workingDir: ./frontend