name: Lint Checks
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  lint:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    # 1. Descarga el código del repositorio
    - uses: actions/checkout@v4

    # 2. Configura Node.js
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # 3. Instala dependencias en /frontend
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    # 4. Ejecuta el linter
    - name: Run Unit Tests
      working-directory: ./frontend
      run: npm run test