name: Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Configura Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # 2. Configura pnpm (esto instala pnpm y configura el caché automáticamente)
      - uses: pnpm/action-setup@v4
        with:
          version: 11.25.0 # O la versión que tengas instalada localmente

      # 3. Instala dependencias con pnpm
      # 'pnpm install' es el equivalente a 'npm ci' (es estricto con el lockfile)
      - name: Install dependencies
        run: pnpm install

      - name: Set environment variables
        run: |
          echo "TEST_API_URL=${{ secrets.TEST_API_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FRONTBUILD_API_URL=${{ secrets.NEXT_PUBLIC_FRONTBUILD_API_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_ENABLE_MSW=${{ secrets.NEXT_PUBLIC_ENABLE_MSW }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FRONTBUILD_HZ_SERVER_URL=${{secrets.NEXT_PUBLIC_FRONTBUILD_HZ_SERVER_URL}}" >> $GITHUB_ENV

      # 4. Ejecuta el linter/test
      - name: Run Unit Tests
        run: pnpm run test